 name = "codeflex"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "codeflex-d1"
database_id = "b630ca67-7a63-48bd-9a5e-a2afc10d56a9"
