/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/byO1wvYMZFH
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Card } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Separator } from "@/components/ui/separator"
import { Button } from "@/components/ui/button"
import { GithubIcon, LeetCodeIcon, CopyIcon} from "./ui/icons"
import { TwitterLogoIcon } from "@radix-ui/react-icons"
import { UserSchema } from "@/actions/types"

export function CompareBox(
  props: {
    src : string;
  }
) {
  return (
    <div className="flex justify-center items-center min-h-screen">
    <Card className="max-w-2xl p-4">
    <img
          src={props.src}
          width={300}
          height={200}
          key={props.src}
          alt="Placeholder"
          className="aspect-[2/1] w-[100vw] object-cover sm:h-[270px] md:w-[516px]"
        />

      <p className="mt-4 text-sm">@fabpot spends 3017% more time coding than tweeting</p>
      
      <Separator className="my-4" />
      
      <div className="flex items-center justify-between mt-4">
        <Button variant="outline">Reload</Button>
        <Button variant="outline">
          <CopyIcon className="w-4 h-4 mr-2" />
          Copy Image
        </Button>
        <Button>
          <TwitterLogoIcon className="w-4 h-4 mr-2" />
          Tweet
        </Button>
      </div>
    </Card>
  </div>
  )
}



